export default () => [
  {
    name: 'Profesional Art Printing Data',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    imageURL: './assets/img/project1-img.png',
    languages: ['css', 'html', 'Bootstrap', 'Ruby'],
    hostedURL: '#',
    githubURL: '#',
  },
  {
    name: 'Profesional Art Printing Data',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    imageURL: './assets/img/project1-img.png',
    languages: ['css', 'html', 'Bootstrap', 'Ruby'],
    hostedURL: '#',
    githubURL: '#',
  },
  {
    name: 'Profesional Art Printing Data',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    imageURL: './assets/img/project1-img.png',
    languages: ['css', 'html', 'Bootstrap', 'Ruby'],
    hostedURL: '#',
    githubURL: '#',
  },
  {
    name: 'Profesional Art Printing Data',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    imageURL: './assets/img/project1-img.png',
    languages: ['css', 'html', 'Bootstrap', 'Ruby'],
    hostedURL: '#',
    githubURL: '#',
  },
  {
    name: 'Profesional Art Printing Data',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    imageURL: './assets/img/project1-img.png',
    languages: ['css', 'html', 'Bootstrap', 'Ruby'],
    hostedURL: '#',
    githubURL: '#',
  },
  {
    name: 'Profesional Art Printing Data',
    description: "A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry's standard",
    imageURL: 'https://res.cloudinary.com/emmii/image/upload/v1649836653/my_portfolio/project_screenshot_ctmepz.png',
    languages: ['css', 'html', 'Bootstrap', 'Ruby'],
    hostedURL: '#',
    githubURL: '#',
  },
  {
    name: 'PM Global Workshop',
    description: "This is a website that provides an overview of an upcoming Project Managers' global workshop. The website shows pertinent information about the workshop, including the program, speakers, sponsors, and contact information.",
    imageURL: 'https://res.cloudinary.com/emmii/image/upload/v1650824023/my_portfolio/pm-global-home_rns1kg.jpg',
    languages: ['HTML', 'CSS', 'Javascript'],
    hostedURL: 'https://emmiiorji.github.io/project-mgt-workshop/',
    githubURL: 'https://github.com/emmiiorji/project-mgt-workshop',
  },
];
